Repository MithishR/Communicado, pull requests merged in 2024-03, with the labels that each got.

#39 Sequence Diagrams
  Scrum Meetings/Scrum meeting week 9.docx
  Scrum Meetings/~$rum meeting week 9.docx
  Sequence Diagrams/Sequence Diagram Use Case 1.jpeg
  Sequence Diagrams/Sequence Diagram Use Case 2.jpeg
Labels: documentation

#44 pages linking fixed
  Django/communicado/pages/templates/pages/home.html
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/templates/pages/signup.html
Labels: bug

#55 Adding down command
  Django/communicado/mac_docker_build_and_run.sh
  Django/communicado/win_docker_build_and_run.bat
Labels: enhancement

#57 database changed and images added
  .DS_Store
  Django/.DS_Store
  Django/communicado/.DS_Store
  Django/communicado/pages/templates/pages/home.html
  Django/media/artexhibition.jpg
  Django/media/fashionshow.jpeg
  Django/media/foodfestival.jpg
  Django/media/musicconcert.jpg
  Django/media/technologyconference.jpeg
  ETicketingDB.sql
Labels: enhancement

#58 Password format changed
  Django/communicado/communicado_eticketing/settings.py
Labels: enhancement

#62 Database Automated Backup Complete
  sqlBackup.md
Labels: documentation, enhancement

#60 Added the GET/POST functionality for signup page, TBD for login page
  Django/communicado/.DS_Store
  Django/communicado/pages/.DS_Store
  Django/communicado/pages/templates/.DS_Store
  Django/communicado/pages/templates/pages/signup.html
  Django/communicado/pages/views.py
Labels: enhancement

#68 As a customer, I want to be able to log in to my account so that I can access my booked events and manage my profile.
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/views.py
Labels: enhancement

#75 Completed the signup page and resolved all conflicts
  Django/communicado/communicado_eticketing/__pycache__/urls.cpython-310.pyc
  Django/communicado/pages/__pycache__/admin.cpython-310.pyc
  Django/communicado/pages/__pycache__/models.cpython-310.pyc
  Django/communicado/pages/__pycache__/urls.cpython-310.pyc
  Django/communicado/pages/__pycache__/views.cpython-310.pyc
  Django/communicado/pages/migrations/__pycache__/__init__.cpython-310.pyc
  Django/communicado/pages/views.py
Labels: enhancement

#79 Events Information
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/urls.cpython-312.pyc
  Django/communicado/communicado_eticketing/settings.py
  Django/communicado/pages/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/__pycache__/apps.cpython-312.pyc
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/templates/pages/i.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: enhancement

#77 Add messages for users to know the state of the application at all times. Also take care of the duplication of entries in the database and model.
  Django/communicado/pages/templates/pages/home.html
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/templates/pages/signup.html
  Django/communicado/pages/views.py
Labels: bug, enhancement

#80 name column added
  Django/communicado/pages/admin.py
  Django/communicado/pages/models.py
  Django/communicado/pages/views.py
Labels: enhancement

#81 Jazzmin setup
  Django/communicado/communicado_eticketing/settings.py
  Django/communicado/requirements.txt
Labels: enhancement

#82 Jazzmin for Django Admin
  Django/communicado/communicado_eticketing/settings.py
Labels: enhancement

#86 Changed and made the UI consistent
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/templates/pages/signup.html
Labels: enhancement

#93 Organizer Actions Implemented
  Django/communicado/pages/templates/pages/add_event.html
  Django/communicado/pages/templates/pages/edit_event.html
  Django/communicado/pages/templates/pages/organizer_actions.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: enhancement

#88 passwords encryption and decryption added
  Django/communicado/pages/templates/pages/home.html
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/views.py
Labels: enhancement

#97 linked organizer to organizer_Actions.html file
  Django/communicado/pages/views.py
Labels: bug

#98 Unit Testing
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-311.pyc
  Django/communicado/pages/tests.py
Labels: enhancement

#101 Category wise searching
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/views.py
Labels: enhancement

#102 Add event completed and functional
  Django/communicado/pages/models.py
  Django/communicado/pages/templates/pages/add_event.html
  Django/communicado/pages/templates/pages/organizer_actions.html
  Django/communicado/pages/views.py
Labels: enhancement

#104 GitHub Action for Pull on Deployment Server
  .github/workflows/pull_on_push.yml
Labels: enhancement

#105 UI added for xyz.html
  Django/communicado/.coverage
  Django/communicado/.coveragerc
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/__pycache__/admin.cpython-312.pyc
  Django/communicado/pages/__pycache__/apps.cpython-312.pyc
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/__pycache__/tests.cpython-312.pyc
  Django/communicado/pages/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/__pycache__/views.cpython-312.pyc
  Django/communicado/pages/migrations/0001_initial.py
  Django/communicado/pages/migrations/__pycache__/0001_initial.cpython-312.pyc
  Django/communicado/pages/migrations/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/static/bg5.jpeg.jpg
  Django/communicado/pages/templates/pages/xyz.html
  Django/communicado/pages/tests.py
Labels: enhancement

#110 Deleting Workflows for Hard Reset
  .github/workflows/pull_on_push.yml
Labels: bug

#109 UI added to pages
  Django/communicado/pages/static/bg4.webp
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/templates/pages/home.html
  Django/communicado/pages/templates/pages/i.html
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/templates/pages/signup.html
Labels: enhancement

#111 Event-search -sparsh
  Django/communicado/.coverage
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/pages/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/__pycache__/apps.cpython-312.pyc
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/views.py
Labels: enhancement

#113 Final Implementation of GitHub Workflow
  .github/workflows/pull_on_push.yml
Labels: enhancement

#118 GitHub Action to Automate tests.py
  .github/workflows/running_tests_py.yml
Labels: enhancement

#120 Resolve errors in Testing
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/communicado_eticketing/settings.py
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/__pycache__/tests.cpython-312.pyc
  Django/communicado/pages/__pycache__/views.cpython-312.pyc
  Django/communicado/pages/migrations/__pycache__/0001_initial.cpython-312.pyc
  Django/communicado/pages/models.py
  Django/communicado/pages/tests.py
  Django/communicado/pages/views.py
Labels: bug

#121 Saving EventOrganizer in the database
  Django/communicado/pages/templates/pages/signup.html
  Django/communicado/pages/views.py
Labels: bug

#122 Testing the UI components for login and signup
  Django/communicado/pages/tests.py
Labels: enhancement

#123 tests added for the login page
  Django/communicado/pages/tests.py
Labels: enhancement

#127 Selenium added to testing
  Django/communicado/pages/tests.py
  Django/communicado/requirements.txt
Labels: enhancement

#131 Fixing UI Testing
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/wsgi.cpython-312.pyc
  Django/communicado/pages/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/__pycache__/apps.cpython-312.pyc
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/__pycache__/views.cpython-312.pyc
  Django/communicado/pages/migrations/0002_alter_admin_user_alter_bookedevent_eventid_and_more.py
  Django/communicado/pages/migrations/__pycache__/0002_alter_admin_user_alter_bookedevent_eventid_and_more.cpython-312.pyc
  Django/communicado/pages/models.py
  Django/communicado/pages/templates/pages/add_to_cart.html
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: bug, enhancement

#133 fixed the UI for events page
  Django/communicado/pages/__pycache__/models.cpython-310.pyc
  Django/communicado/pages/models.py
  Django/communicado/pages/templates/pages/events.html
Labels: bug, enhancement

#137 Basic functionality and working for the Cart page
  Django/communicado/pages/templates/pages/add_to_cart.html
Labels: enhancement

#134 image issue fixed
  Django/communicado/pages/static/hiphopparty.jpeg
  Django/communicado/pages/static/liverpooltrophyparade.jpeg
Labels: bug

#139 Added support files for GitHub Actions
  Django/communicado/Dockerfile.test
  Django/communicado/docker-compose-test.yml
  Django/communicado/mac_test_docker_build_and_run.sh
  Django/communicado/win_test_docker_build_and_run.bat
Labels: enhancement

#138 all tests running
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-310.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-310.pyc
  Django/communicado/pages/__pycache__/__init__.cpython-310.pyc
  Django/communicado/pages/__pycache__/apps.cpython-310.pyc
  Django/communicado/pages/__pycache__/models.cpython-310.pyc
  Django/communicado/pages/migrations/__pycache__/__init__.cpython-310.pyc
  Django/communicado/pages/models.py
  Django/communicado/pages/tests.py
Labels: bug

#148 Added Test Scripting
  Django/communicado/mac_testing.sh
  Django/communicado/win_testing.bat
Labels: enhancement

#149 Created Testing Environment
  .github/workflows/running_tests_py.yml
  Django/communicado/Dockerfile.test
  Django/communicado/docker-compose-test.yml
  Django/communicado/mac_testing.sh
  Django/communicado/win_testing.bat
Labels: enhancement

#147 Retrieve events based on eventOrganizerID in the edit_event
  Django/communicado/pages/views.py
Labels: enhancement

#150 Changed Testing container name
  Django/communicado/mac_testing.sh
Labels: bug

#152 UI testing for add_event page
  Django/communicado/mac_testing.sh
  Django/communicado/pages/tests.py
Labels: enhancement

#156 Sparshuitesting(eventsandeventsinfo)
  Django/communicado/pages/templates/pages/i.html
  Django/communicado/pages/tests.py
Labels: enhancement

#157 Errors made due to revert fixed
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-310.pyc
  Django/communicado/pages/__pycache__/models.cpython-310.pyc
  Django/communicado/pages/static/hiphopparty.jpeg
  Django/communicado/pages/static/liverpooltrophyparade.jpeg
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/templates/pages/home.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: bug

#158 Sparsh(bookeventinfo)
  Django/communicado/pages/models.py
  Django/communicado/pages/templates/pages/userbookinghistory.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: bug, enhancement

#159 User can only book once logged in
  Django/communicado/pages/templates/pages/add_to_cart.html
  Django/communicado/pages/views.py
Labels: bug, enhancement
