Repository MithishR/Communicado, pull requests merged in 2024-04, with the labels that each got.

#167 Add to cart changed for to a proper cart format
  Django/communicado/.coverage
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/__pycache__/admin.cpython-312.pyc
  Django/communicado/pages/__pycache__/apps.cpython-312.pyc
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/__pycache__/tests.cpython-312.pyc
  Django/communicado/pages/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/__pycache__/views.cpython-312.pyc
  Django/communicado/pages/migrations/__pycache__/0001_initial.cpython-312.pyc
  Django/communicado/pages/migrations/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/templates/pages/add_to_cart.html
Labels: enhancement

#170 Added functionality tests for add_events and edit_events
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-310.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-310.pyc
  Django/communicado/communicado_eticketing/__pycache__/urls.cpython-310.pyc
  Django/communicado/pages/__pycache__/__init__.cpython-310.pyc
  Django/communicado/pages/__pycache__/admin.cpython-310.pyc
  Django/communicado/pages/__pycache__/apps.cpython-310.pyc
  Django/communicado/pages/__pycache__/models.cpython-310.pyc
  Django/communicado/pages/__pycache__/tests.cpython-310.pyc
  Django/communicado/pages/__pycache__/urls.cpython-310.pyc
  Django/communicado/pages/__pycache__/views.cpython-310.pyc
  Django/communicado/pages/tests.py
  Django/communicado/pages/views.py
Labels: enhancement

#171 Added User Information page
  .DS_Store
  Django/.DS_Store
  Django/communicado/.DS_Store
  Django/communicado/pages/.DS_Store
  Django/communicado/pages/models.py
  Django/communicado/pages/static/.DS_Store
  Django/communicado/pages/static/icon.png
  Django/communicado/pages/templates/pages/useraccount.html
  Django/communicado/pages/templates/pages/userbookinghistory.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: bug, enhancement

#174 Fixed testing issues
  Django/communicado/pages/tests.py
  Django/communicado/pages/views.py
Labels: bug

#175 Updated Tests.py for useraccount
  Django/communicado/pages/tests.py
Labels: enhancement

#179 payment page added with completed functionality
  Django/communicado/pages/models.py
  Django/communicado/pages/static/payment.jpeg
  Django/communicado/pages/templates/pages/add_to_cart.html
  Django/communicado/pages/templates/pages/home.html
  Django/communicado/pages/templates/pages/payment.html
  Django/communicado/pages/tests.py
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: enhancement

#180 Fixed Bugs and added functionality
  Django/communicado/pages/models.py
  Django/communicado/pages/templates/pages/userbookinghistory.html
  Django/communicado/pages/views.py
Labels: bug, enhancement

#182 Implemented Automated Coverage Testing
  .github/workflows/coverage_testing.yml
  Django/communicado/communicado_eticketing/settings.py
  Django/communicado/venv/Lib/site-packages/_distutils_hack/__pycache__/__init__.cpython-311.pyc
Labels: enhancement

#183 Implemented - 'Push to production only after tests pass'
  .github/workflows/pull_on_push.yml
  .github/workflows/running_tests_py.yml
Labels: enhancement

#184 tests added for xyz.html page
  Django/communicado/pages/tests.py
  Django/communicado/pages/views.py
Labels: enhancement

#186 Updated tests.py
  Django/communicado/pages/tests.py
Labels: enhancement

#188 Implemented Testing across all Branches
  .github/workflows/coverage_testing.yml
  .github/workflows/pull_on_push.yml
  .github/workflows/running_tests_py.yml
Labels: enhancement

#189 link added for user account
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/templates/pages/i.html
Labels: enhancement

#192 Created an admin page
  .github/workflows/running_tests_py.yml
  Django/communicado/pages/models.py
  Django/communicado/pages/templates/pages/admin_actions.html
  Django/communicado/pages/templates/pages/pending.html
  Django/communicado/pages/templates/pages/rejected.html
  Django/communicado/pages/templates/pages/signup.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: enhancement

#198 confirmation page added
  Django/communicado/pages/templates/pages/confirmation.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: enhancement

#203 Fixed Test Database Problems
  .github/workflows/coverage_testing.yml
  .github/workflows/pull_on_push.yml
  .github/workflows/running_tests_py.yml
Labels: bug, enhancement

#201 AdminID of the admin who approved the event added in database
  Django/communicado/pages/views.py
Labels: bug

#205 CI/CD Patch - No Reviews Needed
  .github/workflows/coverage_testing.yml
  .github/workflows/running_tests_py.yml
Labels: bug

#206 Admin functionality for viewing rejected events & updated event organizer functionality
  Django/communicado/pages/templates/pages/admin_actions.html
  Django/communicado/pages/templates/pages/eventaction.html
  Django/communicado/pages/templates/pages/organizer_actions.html
  Django/communicado/pages/templates/pages/pending.html
  Django/communicado/pages/templates/pages/rejected.html
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: bug, enhancement

#209 Dynamic Header Implemented
  Django/communicado/pages/static/logo.jpg
  Django/communicado/pages/templates/pages/add_event.html
  Django/communicado/pages/templates/pages/add_to_cart.html
  Django/communicado/pages/templates/pages/admin_actions.html
  Django/communicado/pages/templates/pages/change_event.html
  Django/communicado/pages/templates/pages/confirmation.html
  Django/communicado/pages/templates/pages/edit_event.html
  Django/communicado/pages/templates/pages/eventaction.html
  Django/communicado/pages/templates/pages/events.html
  Django/communicado/pages/templates/pages/header.html
  Django/communicado/pages/templates/pages/i.html
  Django/communicado/pages/templates/pages/login.html
  Django/communicado/pages/templates/pages/organizer_actions.html
  Django/communicado/pages/templates/pages/pending.html
  Django/communicado/pages/templates/pages/rejected.html
  Django/communicado/pages/templates/pages/signup.html
  Django/communicado/pages/templates/pages/useraccount.html
  Django/communicado/pages/templates/pages/userbookinghistory.html
  Django/communicado/pages/templates/pages/xyz.html
  Django/communicado/pages/views.py
Labels: enhancement

#213 Implement Admin Verification for Updated Events
  Django/communicado/pages/views.py
Labels: bug, enhancement

#218 Database Testing Workflow Created
  .github/workflows/database_testing.yml
Labels: enhancement

#219 UI improved for useraccount page
  Django/communicado/pages/static/mahi.jpeg
  Django/communicado/pages/static/mithish.jpeg
  Django/communicado/pages/static/ojus.jpeg
  Django/communicado/pages/static/pratham.jpeg
  Django/communicado/pages/static/sparsh.png
  Django/communicado/pages/templates/pages/useraccount.html
Labels: enhancement

#220 added a better successful message
  Django/communicado/pages/views.py
Labels: enhancement

#222 Tests added for Confirmation page
  Django/communicado/pages/tests.py
  Django/communicado/pages/views.py
Labels: enhancement

#221 Header UI Testing Implemented
  Django/communicado/pages/templates/pages/header.html
  Django/communicado/pages/tests.py
Labels: enhancement

#223 UI testing added for useraccount page
  Django/communicado/pages/tests.py
Labels: enhancement

#224 Implemented Logout Testing
  Django/communicado/pages/tests.py
Labels: enhancement

#226 Admin functionality testing
  Django/communicado/pages/tests.py
Labels: documentation, enhancement

#230 Edit Account Personal Details
  Django/communicado/pages/templates/pages/edit.html
  Django/communicado/pages/templates/pages/editacc.html
  Django/communicado/pages/templates/pages/useraccount.html
  Django/communicado/pages/tests.py
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: enhancement

#234 Updated tests.py
  Django/communicado/pages/tests.py
Labels: enhancement

#232 Database imp cart
  Django/communicado/communicado_eticketing/__pycache__/__init__.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/settings.cpython-312.pyc
  Django/communicado/communicado_eticketing/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/Testing/Dockerfile
  Django/communicado/pages/Testing/check_db_connection.py
  Django/communicado/pages/Testing/mac_database_testing.sh
  Django/communicado/pages/Testing/win_database_testing.bat
  Django/communicado/pages/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/__pycache__/admin.cpython-312.pyc
  Django/communicado/pages/__pycache__/apps.cpython-312.pyc
  Django/communicado/pages/__pycache__/models.cpython-312.pyc
  Django/communicado/pages/__pycache__/urls.cpython-312.pyc
  Django/communicado/pages/__pycache__/views.cpython-312.pyc
  Django/communicado/pages/migrations/__pycache__/__init__.cpython-312.pyc
  Django/communicado/pages/templates/pages/add_to_cart.html
  Django/communicado/pages/views.py
Labels: enhancement

#239 Testingcart
  Django/communicado/pages/tests.py
Labels: enhancement

#236 Removed View Cart from Header
  Django/communicado/pages/templates/pages/header.html
  Django/communicado/pages/tests.py
Labels: bug

#241 User delete booking and isPaid database addition
  Django/communicado/pages/templates/pages/userbookinghistory.html
  Django/communicado/pages/tests.py
  Django/communicado/pages/urls.py
  Django/communicado/pages/views.py
Labels: bug, enhancement

#242 Total price calculated correctly
  Django/communicado/pages/templates/pages/add_to_cart.html
Labels: bug, enhancement

#243 Email Notification Setup
  Django/communicado/communicado_eticketing/settings.py
  Django/communicado/pages/views.py
Labels: enhancement

#245 confirmation_page
  Django/communicado/communicado_eticketing/settings.py
  Django/communicado/pages/static/siuuu.gif
  Django/communicado/pages/templates/pages/confirmation.html
Labels: bug, enhancement
